export const WORKIES_ROOMS = [
  { room_number: "1", room_label: "V - O1", room_area: "משרדים" },
  { room_number: "2", room_label: "IV - O2", room_area: "משרדים" },
  { room_number: "3", room_label: "IV - O3", room_area: "משרדים" },
  { room_number: "4", room_label: "IV - O4", room_area: "משרדים" },
  { room_number: "5", room_label: "IV - O5", room_area: "משרדים" },
  { room_number: "6", room_label: "VI + VIEW - O6 - בקר", room_area: "משרדים" },
  { room_number: "7", room_label: "V+ - O7", room_area: "משרדים" },
  { room_number: "8", room_label: "CONFERENCE - O8", room_area: "חדרי ישיבות" },
  { room_number: "9", room_label: "I - O9", room_area: "משרדים" },
  { room_number: "10", room_label: "II - O10", room_area: "משרדים" },
  { room_number: "11", room_label: "II - O11", room_area: "משרדים" },
  { room_number: "12", room_label: "II - O12", room_area: "משרדים" },
  { room_number: "13", room_label: "I - O13", room_area: "משרדים" },
  { room_number: "14", room_label: "II - O14 - בקר", room_area: "משרדים" },
  { room_number: "15", room_label: "II - O15", room_area: "משרדים" },
  { room_number: "16", room_label: "II - O16", room_area: "משרדים" },
  { room_number: "17", room_label: "II - O17 - בקר", room_area: "משרדים" },
  { room_number: "18", room_label: "II - O18", room_area: "משרדים" },
  { room_number: "19", room_label: "II - O19", room_area: "משרדים" },
  { room_number: "20", room_label: "II - O20", room_area: "משרדים" },
  { room_number: "21", room_label: "I - O21", room_area: "משרדים" },
  { room_number: "22", room_label: "22 II מורחב", room_area: "משרדים" },
  { room_number: "23", room_label: "23 II מורחב", room_area: "משרדים" },
  { room_number: "24", room_label: "24 II מורחב", room_area: "משרדים" },
  { room_number: "25", room_label: "25 II מורחב", room_area: "משרדים" },
  { room_number: "26", room_label: "26 CONFERENCE - בקר", room_area: "חדרי ישיבות" },
  { room_number: "27", room_label: "27 II מורחב - בקר", room_area: "משרדים" },
  { room_number: "28", room_label: "28 CONFERENCE", room_area: "חדרי ישיבות" },
  { room_number: "29", room_label: "29 II מורחב", room_area: "משרדים" },
  { room_number: "30", room_label: "30 II מורחב", room_area: "משרדים" },
  { room_number: "31", room_label: "31 VI + VIEW", room_area: "משרדים" },
  { room_number: "32", room_label: "32 I", room_area: "משרדים" },
  { room_number: "33", room_label: "בקר - 33 IV +", room_area: "משרדים" },
  { room_number: "34", room_label: "34 I - בקר", room_area: "משרדים" },
  { room_number: "35", room_label: "35 IV +", room_area: "משרדים" },
  { room_number: "36", room_label: "36 VI + VIEW", room_area: "משרדים" },
  { room_number: "37", room_label: "37 I", room_area: "משרדים" },
  { room_number: "38", room_label: "38 III - בקר", room_area: "משרדים" },
  { room_number: "39", room_label: "39 I", room_area: "משרדים" },
  { room_number: "40", room_label: "40 I", room_area: "משרדים" },
  { room_number: "41", room_label: "41 I", room_area: "משרדים" },
  { room_number: "42", room_label: "42 I", room_area: "משרדים" },
  { room_number: "43", room_label: "43 I - בקר", room_area: "משרדים" },
  { room_number: "44", room_label: "44 I", room_area: "משרדים" },
  { room_number: "45", room_label: "45 I", room_area: "משרדים" },
  { room_number: "46", room_label: "46 III", room_area: "משרדים" },
  { room_number: "47", room_label: "47 III", room_area: "משרדים" },
  { room_number: "48", room_label: "48 III", room_area: "משרדים" },
  { room_number: "49", room_label: "49 I", room_area: "משרדים" },
  { room_number: "50", room_label: "50 CHILL - בקר", room_area: "חללים משותפים" },
  { room_number: "51", room_label: "51 I", room_area: "משרדים" },
  { room_number: "52", room_label: "52 II", room_area: "משרדים" },
  { room_number: "53", room_label: "53 II", room_area: "משרדים" },
  { room_number: "54", room_label: "54 V", room_area: "משרדים" },
  { room_number: "55", room_label: "55 III בקר", room_area: "משרדים" },
  { room_number: "56", room_label: "56 III", room_area: "משרדים" },
  { room_number: "57", room_label: "57 II", room_area: "משרדים" },
  { room_number: "58", room_label: "II 58 בקר", room_area: "משרדים" },
  { room_number: "59", room_label: "59 II", room_area: "משרדים" },
  { room_number: "60", room_label: "60 II", room_area: "משרדים" },
  { room_number: "61", room_label: "61 III", room_area: "משרדים" },
  { room_number: "62", room_label: "62 III", room_area: "משרדים" },
  { room_number: "63", room_label: "63 III", room_area: "משרדים" },
  { room_number: "64", room_label: "64 III", room_area: "משרדים" },
  { room_number: "65", room_label: "65 II", room_area: "משרדים" },
  { room_number: "66", room_label: "66 II", room_area: "משרדים" },
  { room_number: "67", room_label: "67 II", room_area: "משרדים" },
  { room_number: "68", room_label: "68 II", room_area: "משרדים" },
  { room_number: "69", room_label: "69 IV", room_area: "משרדים" },
  { room_number: "70", room_label: "70 CONFERENCE", room_area: "חדרי ישיבות" },
  { room_number: "71", room_label: "71 III", room_area: "משרדים" },
  { room_number: "72", room_label: "72 III", room_area: "משרדים" },
  { room_number: "73", room_label: "מס' 73 - III", room_area: "משרדים" },
  { room_number: "74", room_label: "מס' 74 - בקר", room_area: "משרדים" },
  { room_number: "75", room_label: "מס' 75 - IV", room_area: "משרדים" },
  { room_number: "76", room_label: "מס' 76 - I+", room_area: "משרדים" },
  { room_number: "77", room_label: "מס' 77 - II+", room_area: "משרדים" },
  { room_number: "78", room_label: "מס' 78 II", room_area: "משרדים" },
  { room_number: "79", room_label: "מס' 79 - II+ - בקר", room_area: "משרדים" },
  { room_number: "80", room_label: "מס' 80 II - בקר", room_area: "משרדים" },
  { room_number: "81", room_label: "מס' 81 I+", room_area: "משרדים" },
  { room_number: "82", room_label: "מס' 82 - II", room_area: "משרדים" },
  { room_number: "83", room_label: "מס' 83 - III", room_area: "משרדים" },
  { room_number: "84", room_label: "מס' 84 - I+", room_area: "משרדים" },
  { room_number: "85", room_label: "מס' 85 +IV - בקר", room_area: "משרדים" },
  { room_number: "101", room_label: "101 III", room_area: "משרדים" },
  { room_number: "102", room_label: "102 III", room_area: "משרדים" },
  { room_number: "103", room_label: "103 II", room_area: "משרדים" },
  { room_number: "104", room_label: "104 II - בקר", room_area: "משרדים" },
  { room_number: "105", room_label: "105 II", room_area: "משרדים" },
];

export const WORKIES_PUBLIC_AREAS = [
  { area_key: "corridor_a", area_label: "מעבר A", room_area: "מעברים", requires_near_room: true },
  { area_key: "corridor_b", area_label: "מעבר B", room_area: "מעברים", requires_near_room: true },
  { area_key: "corridor_c", area_label: "מעבר C", room_area: "מעברים", requires_near_room: true },
  { area_key: "corridor_d", area_label: "מעבר D", room_area: "מעברים", requires_near_room: true },
  { area_key: "wc", area_label: "WC", room_area: "שירותים", requires_location: true },
  { area_key: "lounge", area_label: "LOUNGE", room_area: "חללים משותפים" },
  { area_key: "traklin", area_label: "TRAKLIN", room_area: "חללים משותפים" },
  { area_key: "bar", area_label: "BAR", room_area: "בר / מטבחון" },
  { area_key: "my_bar", area_label: "MY BAR", room_area: "בר / מטבחון" },
  { area_key: "entrance_hall", area_label: "ENTRANCE HALL", room_area: "חללים משותפים" },
  { area_key: "chill_room", area_label: "CHILL ROOM", room_area: "חללים משותפים" },
  { area_key: "w1_conference", area_label: "W1 CONFERENCE", room_area: "חדרי ישיבות" },
  { area_key: "w2_big_conference", area_label: "W2 BIG CONFERENCE", room_area: "חדרי ישיבות" },
  { area_key: "w3_conference", area_label: "W3 CONFERENCE", room_area: "חדרי ישיבות" },
];

// Location type display labels
export const LOCATION_TYPE_LABELS = {
  room: "חדר / משרד",
  guest: "אורח",
  openspace: "Open Space",
  event: "אירוע",
  none: "לא מוגדר",
};